### PR TITLE
Your DiscordToS code seems interesting

### PR DESCRIPTION
**Pull request by IchimakiKasura**
Hi [Creator ](https://github.com/IchimakiKasura)of [kasu.nhentaiapi.js ](https://github.com/IchimakiKasura/kasu.nhentaiapi.js) here!

After looking on your code I saw this "Discord ToS" It seems kinda cool to add/implement it directly to my API module.

Instead of doing the `includes` in your code you can just add a `true` boolean like `getID(number,true)` because it will automatically throw an error so try adding `try{}catch(){}`

example:
try {

   api.getID(number, true).list(data => {
       data.id _// blah blah blah_
   })
   
} catch(e) {

   console.log(e) _// will send a short messeage_
   _// DISCORD ToS: The doujin picked has a Tag that isn't allowed on Discord_

} 

You can try the experimental version of my repo by cloning it and replacing it to your node_modules folder.
NOTE: before you merge it clone my [repo](https://github.com/IchimakiKasura/kasu.nhentaiapi.js) first for actually to work

Once I published the new version you can update it and I will give you credit.

### CODE REVIEW

**Comment by crackheadakira** [comment]
Wow, I'm surprised you found something that could be added to the API as I used this bot to learn coding, so I didn't ( still don't entirely ) have a grasp on coding.

As of now with the experimental API I keep getting an error:
```UnhandledPromiseRejectionWarning: DISCORD ToS: The doujin picked has a Tag that isn't allowed on Discord```

**Comment by IchimakiKasura** [comment]
Maybe you're doing it wrong? It works for me tho
image
image

Or maybe the Doujin your getting always had those Words that is blocked? cuz' I run the test like 4 times to get a clean Doujin tags

**Comment by crackheadakira** [comment]
(pog astolfo bg)

I was trying to use it with the edited command code from the fork, so I'm not really sure.

**Comment by IchimakiKasura** [comment]
Oh yeah I change the way how to enable the "DiscordTOSchecker" by doing the `api.IsDiscord = true`
image

So that you will no longer add the `,true` on every end of the api modules. You'll now only have to put the `try{ } catch(e){ }` to catch the `DISCORD ToS: The doujin picked has a Tag that isn't allowed on Discord` error and replace it with your warning or the discord embed.

I'll just gonna finish my code this week and might release the 2.9 on Saturday.

**Comment by crackheadakira** [comment]
Thank you so much for implementing the Discord ToS feature!

**Comment by IchimakiKasura** [comment]
the [2.9.0](https://github.com/IchimakiKasura/kasu.nhentaiapi.js) version is here tho you can try it now. also you can close this PR

**Pull request closed without merging**
